# -*- coding: utf-8 -*-
"""BigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HN9CEAdPlPRQzRWlfzmM0tMVBhMen5mz

Загрузите датасет по ценам на жилье Airbnb, доступный на kaggle.com: https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data; Используя Python, реализуйте скрипт mapper.py и reducer.py для расчета, и с помощью MapReduce расчитайте среднее значение и дисперсию по признаку “price” (возможно потребуются ассимптотические формулы для дисперсии);

Подсчитайте среднее значение и дисперсию по признаку “price” в Hive
"""

import pandas as pd
import sys
import numpy as np

data = pd.read_csv('https://raw.githubusercontent.com/olesybabaeva/data/refs/heads/main/AB_NYC_2019.csv')
data

# вычисление среднего значения
data['price'].mean()

# вычисление дисперсии
data['price'].var()